### ISSUE TITLE
Tikz files

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/language-latex2e#10]
It would be nice to get syntax coloring automatically from `.tikz` files like in `language-latex` (see  area/language-latex#81)

**Comment by Aerijo** [comment]
Doesn't it already?

**Comment by PierreMarchand20** [comment]
Well, it did not do it for me, and actually, it is not mentionned in the settings:
![capture d ecran 2018-02-05 a 13 16 35](https://user-images.githubusercontent.com/15056323/35804158-d6e9895a-0a76-11e8-80b5-e03d959f4021.png)

**Comment by Aerijo** [comment]
`.tikz` files should be highlighted by the dedicated grammar in this package (which is admittedly lacking/somewhat broken right now).

Could you paste a screenshot of a `.tikz` file?

**Comment by PierreMarchand20** [comment]
Well it is working for me, it just does not associate automatically `.tikz` files with this grammar

![capture d ecran 2018-02-05 a 13 56 30](https://user-images.githubusercontent.com/15056323/35805495-6462e5e2-0a7c-11e8-8ef9-b4135ab47842.png)

**Comment by Aerijo** [comment]
What is the scope between a pair of `()`?

**Comment by PierreMarchand20** [comment]
![capture d ecran 2018-02-05 a 13 59 12](https://user-images.githubusercontent.com/15056323/35805605-d16b44e0-0a7c-11e8-89e4-c11842dc427e.png)

**Comment by Aerijo** [comment]
So it is applied in your example, but were you saying that it doesn't automatically work when the file ends in `.tikz`?

**Comment by PierreMarchand20** [comment]
Yes, just that :-) sorry if I was not clear

**Comment by Aerijo** [comment]
That's strange. This is what I get upon opening a `.tikz` file.

<img width="915" alt="screen shot 2018-02-05 at 11 04 01 pm" src="https://user-images.githubusercontent.com/22167388/35805784-e59643a6-0ac8-11e8-8b1d-5fd30fce90af.png">

I didn't need to do anything to apply the grammar.

**Comment by PierreMarchand20** [comment]
Indeed, I see that you updated your package but I got the following error:

> npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "***/.atom/.apm/.apmrc" "--userconfig" "***/.atom/.apmrc" "install" "/private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/d-11815-1794-1syb7uu.1qfdnghkt9/package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/tree-sitter-latex2e
npm ERR! 404 
npm ERR! 404  'tree-sitter-latex2e' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'language-latex2e'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

> npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-11815-1794-

**Comment by Aerijo** [comment]
OK, patch released.

**Comment by PierreMarchand20** [comment]
With the last patch, I got the following:
![capture d ecran 2018-02-05 a 14 13 47](https://user-images.githubusercontent.com/15056323/35806153-d9bc10f0-0a7e-11e8-9c4d-3d7f54e5714a.png)

**Comment by Aerijo** [comment]
Yeah, my colours are defined in my stylesheet. The extra green you're seeing is a side effect of my not-so-thought-through built in style attempt.

More importantly, was that automatically applied?

**Comment by PierreMarchand20** [comment]
Oh well, I like it like that xD But no, I need to set the type of file, it does not find it with `auto-detect`. That being said, I just need to it once per file

**Comment by Aerijo** [comment]
OK, was able to reproduce for a brand new `.tikz` file. I'll investigate it tomorrow though, it's getting late here.

FYI, I use the following stylesheet.
```less
@first: #FF9420;	/* Main Primary color */
@second: #FF7F20;	/* Main Secondary color (1) */
@third: #FF6320;	/* Main Secondary color (2) */
@fourth: #FF3F20;	/* Main Complement color */

atom-text-editor .syntax--variable.syntax--parameter {
  &.syntax--optional {
    color: hsl(355, 65%, 65%);
  }

  &.syntax--hashtag {
    color: hsl(29, 54%, 61%);
    &.syntax--1 {
      color: @first;
    }
    &.syntax--2 {
      color: @second;
    }
    &.syntax--3 {
      color: @third;
    }
  }
}

atom-text-editor .syntax--text.syntax--tex.syntax--latex .syntax--punctuation.syntax--definition {
  &.syntax--arguments {
    color: hsl(39, 67%, 69%);
  }

  &.syntax--optional {
    color: hsl(29, 54%, 61%);
  }

  &.syntax--begin.syntax--coordinate.syntax--tikz,
  &.syntax--end.syntax--coordinate.syntax--tikz {
    color: lighten(rgb(106, 0, 108), 20%);
  }
}

atom-text-editor .syntax--text.syntax--tex.syntax--latex .syntax--markup.syntax--other.syntax--coordinate.syntax--tikz {
  color: lighten(rgb(106, 0, 108), 50%);
}
```
